name: Security Pipe

on:
  push:
    branches:
      - main

jobs:
  clone-repository:
    name: Clone Bitbucket Repository
    runs-on: self-hosted
    steps:
      - name: Clone repository
        run: |
          git -c core.sshCommand="ssh -i /home/hebert.cardoso@sp01.local/.ssh/id_rsa" clone git@bitbucket.org:feedz-workspace/feedz-horusec-image.git
          ls
          
  build-docker-image:
    name: Build Docker Image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          cd ~/Documentos/devsecops/actions-runner/_work/horusec-actions/horusec-actions/.github/workflows
          docker build -t horusec-custom .
